steps:
- id: 'Copy credentials from private GCS storage'
  name: gcr.io/cloud-builders/gsutil
  args: ["cp","gs://next2018-demo-bazel/creds/demo-creds.json","./creds/"]
- id: 'Bazel: Test TensorFlow/core'
  name: gcr.io/cloud-builders/bazel
  entrypoint: 'sh' #pass commands directly to shell
  args:
  - '-c'
  - |
    bazel --nomaster_bazelrc --bazelrc=.bazelrc_rbe test //tensorflow/core/...
