steps:
- id: 'Bazel: Test TensorFlow/core'
  name: gcr.io/cloud-builders/bazel
  entrypoint: 'sh' #pass commands directly to shell
  args:
  - 'c'
  - |
    bazel --nomaster_bazelrc --bazelrc=.bazelrc_rbe test //tensorflow/core/...
